@startuml setup

!include <logos/firefox>
title VSCode Startup Sequence for Laminar Form Derivation

actor User
participant "VSCode" as vscode


control "Tasks" as demo
participant "Scala CLI" as scalaCLI
control "runDemo" as runDemo
control "fastLink" as fastLink
control "npmDev" as npmDev
participant "sbt" as sbt
participant "Vite" as Vite
participant "<$firefox>" as firefox

User -> vscode: Opens project folder
activate vscode

vscode -> demo: folderOpen

demo -> scalaCLI: setup
deactivate vscode
activate scalaCLI
'scalaCLI -> scalaCLI: setup.sc
note right: <b>npm i / sbt</b>
scalaCLI -> demo
deactivate scalaCLI
demo -> runDemo
activate runDemo
runDemo -> npmDev
activate npmDev
runDemo -> fastLink
deactivate runDemo
activate fastLink
note left: <b>wait fastOptJS</b>
activate fastLink #LightBlue
activate Vite
npmDev -/ Vite

activate sbt

Vite -> sbt: fastOptJS
sbt -/ fastLink
deactivate fastLink

loop
fastLink -/ sbt: ~client/fastLinkJS
    sbt -> Vite: export ESModule
    Vite -> firefox
end
 deactivate Vite
 deactivate sbt
@enduml
