name: CI

on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: |
          cd example/client
          npm install
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "zulu"
      # - name: Tests
      #   run: sbt +test
      - name: server/dist
        run: sbt server/dist
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
