name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    if: github.event.base_ref=='refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "zulu"
      # - name: Tests
      #   run: sbt +test
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          NODE_OPTIONS: "--openssl-legacy-provider"
